INSERT INTO Districts (CountryCode, DistrictCode, Name) VALUES
    ('PT', '01', 'Aveiro'),
    ('PT', '02', 'Beja'),
    ('PT', '03', 'Braga'),
    ('PT', '04', 'Bragança'),
    ('PT', '05', 'Castelo Branco'),
    ('PT', '06', 'Coimbra'),
    ('PT', '07', 'Évora'),
    ('PT', '08', 'Faro'),
    ('PT', '09', 'Guarda'),
    ('PT', '10', 'Leiria'),
    ('PT', '11', 'Lisboa'),
    ('PT', '12', 'Portalegre'),
    ('PT', '13', 'Porto'),
    ('PT', '14', 'Santarém'),
    ('PT', '15', 'Setúbal'),
    ('PT', '16', 'Viana do Castelo'),
    ('PT', '17', 'Vila Real'),
    ('PT', '18', 'Viseu'),
    ('PT', '31', 'Ilha da Madeira'),
    ('PT', '32', 'Ilha de Porto Santo'),
    ('PT', '41', 'Ilha de Santa Maria'),
    ('PT', '42', 'Ilha de São Miguel'),
    ('PT', '43', 'Ilha Terceira'),
    ('PT', '44', 'Ilha da Graciosa'),
    ('PT', '45', 'Ilha de São Jorge'),
    ('PT', '46', 'Ilha do Pico'),
    ('PT', '47', 'Ilha do Faial'),
    ('PT', '48', 'Ilha das Flores'),
    ('PT', '49', 'Ilha do Corvo');